# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  AZUSER: afaridiaz@gmail.com
  MY_RESOURCE_GROUP: migrupoderecursos
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: crear arquitectura
      uses: actions/setup-node@v3
    - run: az login -u ${{ env.AZUSER }} -p ${{ secrets.AZUSER_PASS }}
    - run: az group create -l westus -n ${{ env.MY_RESOURCE_GROUP }}
    - run: az appservice plan create --resource-group ${{ env.MY_RESOURCE_GROUP }} --name MY_APP_SERVICE_PLAN --is-linux
    - run: az webapp create --name MY_WEBAPP_NAME --plan MY_APP_SERVICE_PLAN --resource-group ${{ env.MY_RESOURCE_GROUP }} --runtime "NODE|18-lts"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: ""
  
